### ISSUE TITLE
How to add Flowbite Svelte UI component

### ISSUE THREAD

**Issue by Sakthivelgovindan** [breadthe/electron-svelte-tailwind2-starter#1]
When I try to install Flowbite Svelte

![image](https://github.com/breadthe/electron-svelte-tailwind2-starter/assets/29191823/c7325f22-8dc2-43d0-a01a-6c8e9c6c41dc)

it throws error

![image](https://github.com/breadthe/electron-svelte-tailwind2-starter/assets/29191823/b95baa8d-d8d6-46b0-9e65-d7fa35e07835)

Electron App Error
![image](https://github.com/breadthe/electron-svelte-tailwind2-starter/assets/29191823/e791bc1c-e393-4d53-83b9-66345e0d7b94)

**Comment by breadthe** [comment]
Sorry mate, this project is no longer maintained. In fact I'll go ahead and archive it.
